[package]
name = "paxconsola"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
maplit = "*"
num-traits = "0.2"
num-derive = "0.3"
glob = "*"
rand = "*"
structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"
lazy_static = "*"
indexmap = "*"
# color-backtrace = { version = "0.3" }
percent-encoding = "*"
itertools = "0.8.2"
petgraph = "0.5.0"
wat = "1"
#wasm3 = { path = "./wasm3-rs" }
#wasm3-sys = { path = "./wasm3-rs/wasm3-sys" }
wasm3 = { git = "https://github.com/Veykril/wasm3-rs", optional = true }
stdweb = { version = "*", optional = true }

[features]
default = ["wasm3"]
