[package]
name = "paxconsolas"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
maplit = "*"
num-traits = "0.2"
num-derive = "0.3"
glob = "*"
termion = "*"
rand = "*"

[[bin]]
name = "vm"
path = "src/vm.rs"
