[package]
name = "forth-rs"
version = "0.1.0"
authors = ["zack <zack.bitcoin@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
maplit = "*"
num-traits = "0.2"
num-derive = "0.3"
glob = "*"

[[bin]]
name = "vm"
path = "src/vm.rs"
