[package]
name = "ide"
version = "0.1.0"
authors = ["Tim Ryan <trim@fb.com>"]
edition = "2018"

[dependencies]
yew = "0.11.0"
paxconsola = { path = "../", default-features = false, features = ["stdweb"] }
stdweb = "*"
indexmap = "*"

[profile.release]
debug = true
