[package]
name = "paxconsola-desktop"
version = "0.1.0"
authors = ["Tim Ryan <tim@timryan.org>"]
edition = "2018"

[dependencies]
ggez = "0.6"
paxforth = { path = "../paxforth" }
anyhow = "1.0.28"
wat = "1"
glam = { version = "0.15", features = ["mint"]}
