all:
	mkdir -p lib
	cd lib; wget https://raw.githubusercontent.com/db48x/emularity/05390a4c915790825b67431803cada9ef66fa97f/browserfs.min.js
	cd lib; wget https://archive.org/download/emularity_engine_v1/dosbox-sync.js.gz; gunzip dosbox-sync.js.gz
	cd lib; wget https://archive.org/download/emularity_engine_v1/dosbox-sync.mem.gz; gunzip dosbox-sync.mem.gz
	cd lib; wget https://raw.githubusercontent.com/db48x/emularity/05390a4c915790825b67431803cada9ef66fa97f/es6-promise.js
	cd lib; wget https://raw.githubusercontent.com/db48x/emularity/05390a4c915790825b67431803cada9ef66fa97f/loader.js
	mkdir -p lib/logo
	cd lib/logo; wget https://raw.githubusercontent.com/db48x/emularity/05390a4c915790825b67431803cada9ef66fa97f/logo/emularity_color_small.png
	cd lib; wget https://archive.org/download/emularity_engine_v1/vice-resid.js.gz; gunzip vice-resid.js.gz
	cd lib; wget https://unpkg.com/wasmboy@0.7.0/dist/wasmboy.ts.umd.js
	cd lib; wget https://raw.githubusercontent.com/Stuk/jszip/master/dist/jszip.min.js
